name: GitHub Actions

run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message,'RELEASE')"
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Run Tests
        run: |
          echo ${{github.ref_name}}
          npm install -s
          npm test
      - name: Bump Version
        run: |
          git config --global user.name 'hadeel-mahmoud'
          git config --global user.email 'nez.hadeel@gmail.com'
          npm version patch -m "[RELEASE] %s"
          git push
